/** Every audited action, so the vocabulary stays consistent and discoverable. */
export const AuditAction = {
  UserSuspended: 'user.suspended',
  UserReactivated: 'user.reactivated',
  OrganizationCreated: 'organization.created',
  OrganizationSuspended: 'organization.suspended',
  OrganizationReactivated: 'organization.reactivated',
  OrganizationRenamed: 'organization.renamed',
  OwnershipTransferred: 'organization.ownership_transferred',
  MemberAdded: 'member.added',
  MemberRoleChanged: 'member.role_changed',
  MemberRemoved: 'member.removed',
  ApiKeyCreated: 'api_key.created',
  ApiKeyRevoked: 'api_key.revoked',
  WalletCreated: 'wallet.created',
  WalletFrozen: 'wallet.frozen',
  WalletUnfrozen: 'wallet.unfrozen',
  WebhookEndpointCreated: 'webhook_endpoint.created',
  WebhookEndpointUpdated: 'webhook_endpoint.updated',
  WebhookEndpointDeleted: 'webhook_endpoint.deleted',
  WebhookSecretRotated: 'webhook_endpoint.secret_rotated',
  WalletPrimaryChanged: 'wallet.primary_changed',
  PayoutDestinationAdded: 'payout_destination.added',
  PayoutDestinationRemoved: 'payout_destination.removed',
  PayoutRequested: 'payout.requested',
  PaymentReleasedEarly: 'payment.released_early',
  RefundRequested: 'refund.requested',
  RefundRetried: 'refund.retried',
  FxRateSet: 'fx.rate_set',
  FeeRuleSet: 'fee_rule.set',
  FeeRuleRetired: 'fee_rule.retired',
  ReconciliationItemResolved: 'reconciliation_item.resolved',
  WebhookReplayed: 'webhook.replayed',
  RefreshTokenReuseDetected: 'auth.refresh_token_reuse_detected',
} as const;

export type AuditActionName = (typeof AuditAction)[keyof typeof AuditAction];
